title = "Wonderland"
keywords = ""
copyright = ""


baseurl = "https://duyizhuo.com"
languageCode = "en-us"
theme = "wonderland"
paginate = 10

disqusShortname = "blog-disqus-com-1"

googleAnalytics = "UA-33561194-4"

[markup.goldmark.renderer]
  unsafe= true

[markup]
  [markup.highlight]
    # codeFences = true
    # guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    # tabWidth = 4

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 1
    pre = "fas fa-star"
  [[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/dyzdyz010"
    weight = 2
    pre = "fab fa-twitter"
  [[menu.main]]
    identifier = "sarahah"
    name = "Leave me a message!"
    url = "https://dyzdyz010.sarahah.com/"
    weight = 3
  [[menu.main]]
    identifier = "more"
    name = "More"
    weight = 4
  [[menu.main]]
    identifier = "hemifuture"
    name = "Hemifuture"
    url = "https://forum.hemifuture.cn"
    parent = "more"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  subtitle = "Personal Blog"
  readMore = "Read more"
  menuMore = "Show more"
  readOtherPosts = "Read other posts"
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"
  [params.logo]
    logoText = "Wonderland"
    logoHomeLink = "/"